name: Release

on:
  push:
    tags: ['*']

jobs:
  alfred-switch-audio:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Build project
        run: make build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/switchaudio.alfredworkflow
          token: ${{ secrets.DEPLOY_TOKEN }}
